spring:
  application:
    name: GeminiDemo
  ai:
    google:
      genai:
        api-key: 'AIzaSyBJm5i6l3taDFiCseV_KdlQgH0H8ciFXmE'
        chat:
          options:
            model: 'gemini-2.5-flash' #'gemini-2.5-pro'